<a href="https://colab.research.google.com/github/Justin-cj07/AIML/blob/main/D5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
lst=[12,23,34,45,56]
lst
pd.Series(lst)

0    12
1    23
2    34
3    45
4    56
dtype: int64

In [ ]:
#one d array
subject=["English","ML","Maths"]
marks=[45,56,67]
gpa=[4.5,5.6,6.7]
pd.Series([subject,marks,gpa])

0    4.5
1    5.6
2    6.7
dtype: float64

In [ ]:

import seaborn as sns
resto=sns.load_dataset("tips")
resto.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.
Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.
Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.
Error: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.

In [ ]:
type(resto)
type(resto.tip)

pandas.core.series.Series

In [ ]:
#no. of rows and column
resto.shape

(244, 7)

In [ ]:
#Check data type of each column
resto.dtypes

total_bill     float64
tip            float64
sex           category
smoker        category
day           category
time          category
size             int64
dtype: object

In [ ]:
#check duplicate data
resto.duplicated().sum()
resto[resto.duplicated()]

Empty DataFrame
Columns: [total_bill, tip, sex, smoker, day, time, size]
Index: []

In [ ]:
#drops duplicate value . To remove permanently apply inplace=True
resto.drop_duplicates()
resto.drop_duplicates(inplace=True)

In [ ]:
resto.duplicated().sum()

np.int64(0)

In [ ]:

#Dataframe using list
subject=["English","ML","Maths"]
marks=[45,56,67]
gpa=[4.5,5.6,6.7]
pd.DataFrame([subject,marks,gpa],index=["subject","marks","gpa"]).T #index to assign names and T for transpose

   subject marks  gpa
0  English    45  4.5
1       ML    56  5.6
2    Maths    67  6.7

In [ ]:
subject={1:"English",2:"ML",3:"Maths"}
marks={1:45,2:56,3:67}
gpa={1:4.5,2:5.6,3:6.7}
pd.DataFrame([subject,marks,gpa],index=["subject","marks","gpa"]).T #index to assign names and T for transpose

   subject marks  gpa
1  English    45  4.5
2       ML    56  5.6
3    Maths    67  6.7

In [ ]:
resto.info()

<class 'pandas.core.frame.DataFrame'>
Index: 243 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  243 non-null    float64
 1   tip         243 non-null    float64
 2   sex         243 non-null    category
 3   smoker      243 non-null    category
 4   day         243 non-null    category
 5   time        243 non-null    category
 6   size        243 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 9.1 KB

In [ ]:
#statistical information
resto.describe()

         sex smoker  day    time
count    243    243  243     243
unique     2      2    4       2
top     Male     No  Sat  Dinner
freq     157    151   87     176

In [ ]:
resto.describe(include="category")

         sex smoker  day    time
count    243    243  243     243
unique     2      2    4       2
top     Male     No  Sat  Dinner
freq     157    151   87     176

In [ ]:
#indexing and slicing

resto.head(2)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

In [ ]:
resto[10:15] #1d slicing

    total_bill   tip     sex smoker  day    time  size
10       10.27  1.71    Male     No  Sun  Dinner     2
11       35.26  5.00  Female     No  Sun  Dinner     4
12       15.42  1.57    Male     No  Sun  Dinner     2
13       18.43  3.00    Male     No  Sun  Dinner     4
14       14.83  3.02  Female     No  Sun  Dinner     2

In [ ]:
resto.iloc[10:15,0:2]#prints the index based location
resto.iloc[10:15,[0,2,4]]#prints individual columns

    total_bill     sex  day
10       10.27    Male  Sun
11       35.26  Female  Sun
12       15.42    Male  Sun
13       18.43    Male  Sun
14       14.83  Female  Sun

In [ ]:
resto.loc[10:15,"total_bill"] #need to specify the column
resto.loc[10:15,["total_bill","tip"]]

    total_bill   tip
10       10.27  1.71
11       35.26  5.00
12       15.42  1.57
13       18.43  3.00
14       14.83  3.02
15       21.58  3.92

In [ ]:
resto.tail(1)

     total_bill  tip     sex smoker   day    time  size
243       18.78  3.0  Female     No  Thur  Dinner     2

In [ ]:
resto.loc[244]=[20.54,2.0,"Male","Yes","Sat","Lunch",1]
resto.tail(2)

     total_bill  tip     sex smoker   day    time  size
243       18.78  3.0  Female     No  Thur  Dinner     2
244       20.54  2.0    Male    Yes   Sat   Lunch     1

In [ ]:
resto["Bill_per_size"]=resto.total_bill/resto.size
resto.head()

     total_bill   tip     sex smoker   day    time  size  Bill_per_size
0         16.99  1.01  Female     No   Sun  Dinner     2       8.703893
1         10.34  1.66    Male     No   Sun  Dinner     3       5.297131
2         21.01  3.50    Male     No   Sun  Dinner     3      10.763320
3         23.68  3.31    Male     No   Sun  Dinner     2      12.131148
4         24.59  3.61  Female     No   Sun  Dinner     4      12.597336
..          ...   ...     ...    ...   ...     ...   ...            ...
240       27.18  2.00  Female    Yes   Sat  Dinner     2      13.924180
241       22.67  2.00    Male    Yes   Sat  Dinner     2      11.613730
242       17.82  1.75    Male     No   Sat  Dinner     2       9.129098
243       18.78  3.00  Female     No  Thur  Dinner     2       9.620902
244       20.54  2.00    Male    Yes   Sat   Lunch     1      10.522541

[244 rows x 8 columns]

In [ ]:
#data sorting
resto.sort_values(by="total_bill",ascending=False,ignore_index=True)

     total_bill    tip     sex smoker   day    time  size  Bill_per_size
0         50.81  10.00    Male    Yes   Sat  Dinner     3      26.029713
1         48.33   9.00    Male     No   Sat  Dinner     4      24.759221
2         48.27   6.73    Male     No   Sat  Dinner     4      24.728484
3         48.17   5.00    Male     No   Sun  Dinner     6      24.677254
4         45.35   3.50    Male    Yes   Sun  Dinner     3      23.232582
..          ...    ...     ...    ...   ...     ...   ...            ...
239        7.51   2.00    Male     No  Thur   Lunch     2       3.847336
240        7.25   1.00  Female     No   Sat  Dinner     1       3.714139
241        7.25   5.15    Male    Yes   Sun  Dinner     2       3.714139
242        5.75   1.00  Female    Yes   Fri  Dinner     2       2.945697
243        3.07   1.00  Female    Yes   Sat  Dinner     1       1.572746

[244 rows x 8 columns]

In [ ]:
text="python is fun to learn"
text
n=text.split()
c1=len(n)
c1
list(map(len,text.split()))

[6, 2, 3, 2, 5]

In [ ]:
#concatenate
ser1=pd.Series([12,13,14,15])
ser2=pd.Series([21,23,24,25])
pd.concat([ser1,ser2],keys=["ser1","ser2"],axis=1) #keys is to display the name of column. Axis 0 or 1 is to concat them vertically or horizontally

   ser1  ser2
0    12    21
1    13    23
2    14    24
3    15    25